name: Daily Backtest
on:
  schedule:
    - cron: '0 8 * * *'  # 8 AM UTC daily
  workflow_dispatch:
jobs:
  backtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run backtest
        run: python backtest.py
      - name: Commit and push results
        run: |
          git config --global user.name "Automated Backtest"
          git config --global user.email "actions@users.noreply.github.com"
          git add output/* data/*
          git commit -m "Daily backtest update $(date +'%Y-%m-%d')"
          git push
